export const tokens = {
  colors: {
    ink: "#151718",
    muted: "#667078",
    paper: "#fbfaf7",
    panel: "#ffffff",
    line: "#ded8cf",
    soft: "#f2eee6",
    accent: "#bd2430",
    accentDark: "#7d1620",
    leaf: "#2f6f52",
    blue: "#254e67",
    gold: "#c68a28",
    greenRibbon: "#dce8e1",
    campaignRibbon: "#eddfce",
    newRibbon: "#eae8ed",
    warmRibbon: "#faf3e6",
  },
  fonts: {
    body: ["Inter", "Arial", "sans-serif"],
    heading: ["Libre Baskerville", "Georgia", "serif"],
    display: ["Domaine Display Narrow", "Libre Baskerville", "serif"],
  },
  fontWeights: {
    body: { regular: 400, semibold: 600, bold: 700, extrabold: 800 },
    heading: { regular: 400, bold: 700 },
    display: { regular: 400, semibold: 600, bold: 700 },
  },
  shadows: {
    card: "drop-shadow(-14px 20px 20px rgba(36,26,16,.25))",
    cardHover: "drop-shadow(-18px 28px 32px rgba(36,26,16,.38))",
    panel: "0 24px 60px rgba(33,27,20,.14)",
  },
  layout: {
    maxWidth: "1320px",
    shellPadding: "28px",
    shellPaddingMobile: "16px",
    sidebarWidth: "260px",
    headerHeight: "84px",
  },
  grid: {
    productColumns: 4,
    productColumnsHome: 5,
    gap: "18px",
    gapHome: "18px",
    gapLarge: "28px",
  },
  transitions: {
    navUnderline: "transform .28s ease",
    cardHover: "filter .35s ease, transform .35s ease",
    cartOverlay: "opacity .22s ease",
  },
  typography: {
    h1Size: "clamp(42px,7vw,78px)",
    h2Size: "28px",
    h3Size: "19px",
    bodySize: "16px",
    bodyLineHeight: 1.45,
    smallSize: "13px",
    captionSize: "11px",
    priceSize: "17px",
    priceLargeSize: "28px",
  },
} as const;
